#!/bin/sh

STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$")

if [[ "$STAGED_GO_FILES" = "" ]]; then
  exit 0
fi

GOLANGCI_LINT=$GOPATH/bin/golangci-lint

# Check for golangci-lint
if [[ ! -x "$GOLANGCI_LINT" ]]; then
  printf "Please install golangci-lint (go get -u github.com/golangci/golangci-lint/cmd/golangci-lint)"
  exit 1
fi

printf "Running golangci-lint on all staged *.go files...\n"

golangci-lint run 
if [ $? != 0 ]; then
  printf "Linting failed! Please fix errors before committing.\n"
  exit 1
else
 printf "Linting passed! Continuing to commit.\n"
fi