/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/categories/": {
    /** Get all categories */
    get: operations["getCategories"];
  };
  "/api/v1/categories/:id": {
    /** Get category by id */
    get: operations["getOneCategory"];
  };
  "/api/v1/posts/": {
    /** Get post by id */
    get: operations["getPosts"];
    /** Create post */
    post: operations["createPost"];
  };
  "/api/v1/posts/:id": {
    /** Get region by id */
    get: operations["getOnePost"];
  };
  "/api/v1/regions/": {
    /** Get all regions */
    get: operations["getRegions"];
  };
  "/api/v1/regions/:id": {
    /** Get region by id */
    get: operations["getOneRegion"];
  };
  "/api/v1/users/:id": {
    /** Get one user */
    get: operations["getUser"];
  };
  "/api/v1/users/aboutme": {
    /** Sign Up */
    get: operations["aboutme"];
  };
  "/api/v1/users/confirm/:id": {
    /** Validate email */
    post: operations["confirm"];
  };
  "/api/v1/users/signup": {
    /** Sign Up */
    post: operations["signup"];
  };
  "/api/v1/users/validate": {
    /** Resend email */
    get: operations["signin"];
  };
}

export interface definitions {
  /** @description nolint: govet */
  Category: {
    /** Format: date-time */
    CreatedAt?: string;
    /**
     * Format: date-time
     * @description DeletedAt is a pointer because it can be null
     */
    DeletedAt?: string;
    /** Format: uint64 */
    ID?: number;
    Text?: string;
  };
  JWTClaims: {
    /** Format: uint64 */
    ID?: number;
    Name?: string;
    /** Format: uint8 */
    Role?: number;
    Verified?: boolean;
  };
  /** @description nolint: govet */
  Post: {
    Address?: string;
    /** Format: uint64 */
    CategoryID?: number;
    /** Format: date-time */
    CreatedAt?: string;
    /** Format: date-time */
    DeletedAt?: string;
    Description?: string;
    /** Format: date-time */
    Expiry?: string;
    /** Format: uint64 */
    ID?: number;
    /** Format: float */
    Latitude?: number;
    /** Format: float */
    Longitude?: number;
    Photo?: string;
    /** Format: uint64 */
    RegionID?: number;
    Title?: string;
    /** Format: uint64 */
    UserID?: number;
  };
  /** @description nolint: govet */
  Region: {
    /** Format: date-time */
    CreatedAt?: string;
    /**
     * Format: date-time
     * @description DeletedAt is a pointer because it can be null
     */
    DeletedAt?: string;
    /** Format: uint64 */
    ID?: number;
    Text?: string;
  };
  /** @description Standardized http response */
  Response: {
    Message?: string;
  };
  /** @description nolint: govet */
  User: {
    /** Format: date-time */
    CreatedAt?: string;
    /**
     * Format: date-time
     * @description DeletedAt is a pointer because it can be null
     */
    DeletedAt?: string;
    Email?: string;
    /** Format: uint64 */
    ID?: number;
    Name?: string;
    Password?: string;
    Phone?: string;
    Profile?: string;
    /** Format: uint8 */
    Role?: number;
    Verified?: boolean;
  };
}

export interface responses {
  AboutMeSucces: {
    schema: {
      User?: definitions["JWTClaims"];
    };
  };
  GenericResponse: {
    schema: definitions["Response"];
  };
  GetAllCategoriesResponse: {
    schema: definitions["Category"][];
  };
  GetAllPostResponse: {
    schema: definitions["Post"][];
  };
  GetAllRegionsResponse: {
    schema: definitions["Region"][];
  };
  GetOneCategoriesResponse: {
    schema: definitions["Category"];
  };
  GetOnePostResponse: {
    schema: definitions["Post"];
  };
  GetOneRegionsResponse: {
    schema: definitions["Region"];
  };
  GetOneUserResponse: {
    schema: definitions["User"];
  };
  SignInSucces: {
    schema: {
      Token?: string;
    };
  };
  SignUpSucces: {
    schema: {
      Token?: string;
      User?: definitions["User"];
    };
  };
}

export interface operations {
  /** Get all categories */
  getCategories: {
    responses: {
      200: responses["GetAllCategoriesResponse"];
      default: responses["GenericResponse"];
    };
  };
  /** Get category by id */
  getOneCategory: {
    responses: {
      200: responses["GetOneCategoriesResponse"];
      default: responses["GenericResponse"];
    };
  };
  /** Get post by id */
  getPosts: {
    responses: {
      200: responses["GetAllPostResponse"];
      default: responses["GenericResponse"];
    };
  };
  /** Create post */
  createPost: {
    responses: {
      200: responses["GetOnePostResponse"];
      default: responses["GenericResponse"];
    };
  };
  /** Get region by id */
  getOnePost: {
    responses: {
      200: responses["GetOnePostResponse"];
      default: responses["GenericResponse"];
    };
  };
  /** Get all regions */
  getRegions: {
    responses: {
      200: responses["GetAllRegionsResponse"];
      default: responses["GenericResponse"];
    };
  };
  /** Get region by id */
  getOneRegion: {
    responses: {
      200: responses["GetOneRegionsResponse"];
      default: responses["GenericResponse"];
    };
  };
  /** Get one user */
  getUser: {
    responses: {
      200: responses["GetOneUserResponse"];
      default: responses["GenericResponse"];
    };
  };
  /** Sign Up */
  aboutme: {
    responses: {
      200: responses["AboutMeSucces"];
      default: responses["GenericResponse"];
    };
  };
  /** Validate email */
  confirm: {
    responses: {
      200: responses["SignInSucces"];
      default: responses["GenericResponse"];
    };
  };
  /** Sign Up */
  signup: {
    responses: {
      200: responses["SignUpSucces"];
      default: responses["GenericResponse"];
    };
  };
  /** Resend email */
  signin: {
    responses: {
      200: responses["SignInSucces"];
      default: responses["GenericResponse"];
    };
  };
}

export interface external {}
